namespace WMS.Domain.Enums;

public enum UnitTaskTypeCode
{
    INBOUND_APPROVE,
    INBOUND_RECEIVE,
    INBOUND_PUTAWAY,

    OUTBOUND_APPROVE,
    OUTBOUND_PICK,
    OUTBOUND_DISPATCH,

    AUDIT_OPEN,
    AUDIT_COUNT,
    AUDIT_CLOSE
}
