<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\WMS.API\WMS.API.csproj" />
    <ProjectReference Include="..\..\WMS.Infrastructure\WMS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\WMS.Application\WMS.Application.csproj" />
    <ProjectReference Include="..\..\WMS.Domain\WMS.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
